export const colors = {
  background: "#EDF7F5",
  surface: "#FFFFFF",
  surfaceMuted: "#F4FAF9",
  primary: "#2F6F68",
  primaryPressed: "#245A54",
  accent: "#BCE5DF",
  accentStrong: "#79C9BE",
  textPrimary: "#18312E",
  textSecondary: "#6C817E",
  border: "#DCEBE8",
  danger: "#B44343",
  white: "#FFFFFF",
  transparent: "transparent",
} as const;
